---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cryptogen-service-deployment
  labels:
    app: cryptogen-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cryptogen-service
    spec:
      containers:
      - name: cryptogen-service
        image: cryptogen-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: ENVIRONMENT
          value: prod
        - name: DB
          value: mongodb-service
        - name: port
          value: 4000
        readinessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: cryptogen-service
  labels:
    app: cryptogen-service
spec:
  selector:
    app: cryptogen-service
  ports:
  - port: 4000
    protocol: TCP
    nodePort: 4000
  type: LoadBalancer