---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-cluster

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-cluster
    spec:
      containers:
      - name: mongo-container
        image: mongo
        args: ["--dbpath", "/data/mongodb"] 
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-cluster-2a
          mountPath: /data
      volumes:
      - name: mongo-cluster-2a
        awsElasticBlockStore:
          volumeID: EBS_VOLUME_ID
          fsType: ext4