---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
    - port: 8300
      targetPort: 8300
      protocol: TCP
      name: vault
  selector:
    app: vault

---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: "vault:1.1.0" 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8300
        env:
        - name: VAULT_LOCAL_CONFIG
          value: '{"listener": [{ "tcp": { "address": "0.0.0.0:8300", "tls_disable": true}}]}'
        command: ["vault", "server", "-dev"]
        readinessProbe:
          tcpSocket:
            port: 8300
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8300
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          capabilities:
            add:
              - IPC_LOCK