---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-cluster
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-cluster-2a
          mountPath: /data
      volumes:
      - name: mongo-cluster-2a
        awsElasticBlockStore:
          volumeID: vol-00d999eaddb2c8aaf
          fsType: ext4
