---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  selector:
    app: mongo-cluster
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
