---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
    - port: 8300
      targetPort: 8300
      protocol: TCP
      name: vault
  selector:
    app: vault