---
apiVersion: v1
kind: Service
metadata:
  name: cryptogen-service
  labels:
    app: cryptogen-service
spec:
  selector:
    app: cryptogen-service
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: LoadBalancer