---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cryptogen-service-deployment
  labels:
    app: cryptogen-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cryptogen-service
    spec:
      containers:
      - name: cryptogen-service
        image: dpk28/cryptogen_service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: DB
          value: "mongodb://mongodb-service:27017/cryptogen"
        - name: KMS_URL
          value: "http://kms-service:4001/api"
        - name: KMS_API_VERSION
          value: "v1"
        - name: PORT
          value: "4000"
        readinessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20