---
apiVersion: v1
kind: Service
metadata:
  name: kms-service
  labels:
    app: kms-service
spec:
  selector:
    app: kms-service
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  type: LoadBalancer
