---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kms-service-deployment
  labels:
    app: kms-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kms-service
    spec:
      containers:
      - name: kms-service
        image: dpk28/kms_service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: VAULT_URL
          value: "http://vault:8200"
        - name: VAULT_API_VERSION
          value: "v1"
        - name: VAULT_TOKEN
          value: "s.HBaAWj6ZuEVdMI09ldTWQ2zN"
        - name: PORT
          value: "4001"
        readinessProbe:
          tcpSocket:
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4001
          initialDelaySeconds: 15
          periodSeconds: 20
